@host = http://seperate.test/api


### test
GET {{host}}/admin/test HTTP/1.1
content-type: application/json

### get captcha
GET {{host}}/admin/captcha HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest



### admin login
# @name login
POST {{host}}/admin/login HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest

{
  "username":"admin",
  "password":"admin"
}

@adminToken = {{login.response.body.$.token.access_token}}
@refreshToken = {{login.response.body.$.token.refresh_token}}


### admin info
POST {{host}}/admin/me HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}



### admin logout
POST {{host}}/admin/logout HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### refresh
POST {{host}}/admin/refresh HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest

{
  "refresh_token": "{{refreshToken}}"
}


### oauth token
POST {{host}}/oauth/token HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache

{
  "grant_type":"password",
  "client_id":"2",
  "client_secret":"Ba2swh9tdizTmw4zetCNUi5d734YtNUk9AqGMRJs",
  "scope":"*",    
  "username":"admin",
  "password":"admin",
  "provider":"admins"
}

### token refresh
POST {{host}}/oauth/token HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache

{
  "grant_type":"refresh_token",
  "client_id":"2",
  "client_secret":"En2SBHawG9VrWrUkJqY0FOZHVklvOsazK4DzCSfG",   
  "provider":"admins",
  "refresh_token": "{{refreshToken}}"
}

### permissions list
GET {{host}}/admin/permissions HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### permission
GET {{host}}/admin/permissions/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### update permission
PATCH {{host}}/admin/permissions/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "remark": "test"
}

### create permission
POST {{host}}/admin/permissions HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "name":"test permission3",
  "guard_name":"admin",
  "description":"test",
  "remark":"test",
  "pid":0,
  "type":1
}

### delete permission
DELETE {{host}}/admin/permissions/5 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete permissions
DELETE {{host}}/admin/permissions/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[8,9]
}

### roles list
GET {{host}}/admin/roles HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### role
GET {{host}}/admin/roles/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### create role
POST {{host}}/admin/roles HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "name":"test Role3",
  "guard_name":"admin",
  "description":"test",
  "remark":"test",
  "pid":0,
  "type":1
}

### update role
PATCH {{host}}/admin/roles/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "remark": "test02"
}

### delete role
DELETE {{host}}/admin/roles/5 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete roles
DELETE {{host}}/admin/roles/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[6]
}

### assign permissions to role
POST {{host}}/admin/roles/assign/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[1,2,3]
}

### admins list
GET {{host}}/admin/admins HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### admin
GET {{host}}/admin/admins/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### create admin
POST {{host}}/admin/admins HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "username":"test admin32",
  "password":"123456"
}


### update admin
PATCH {{host}}/admin/admins/4 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "username": "admin"
}

### delete admin
DELETE {{host}}/admin/admins/4 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete admins
DELETE {{host}}/admin/admins/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[5,6]
}

### modify admin password
POST {{host}}/admin/admins/modify HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "oldpassword":"123123",
  "password":"1231234",
  "password_confirmation":"1231234"
}

### reset admin password
POST {{host}}/admin/admins/reset/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### assign roles to permission
POST {{host}}/admin/roles/assign/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[1,2,3]
}


### adminlogs list
GET {{host}}/admin/adminlogs HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### adminlog
GET {{host}}/admin/adminlogs/11 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}
