@host = http://seperate.test/api


### test
GET {{host}}/admin/test HTTP/1.1
content-type: application/json

### get captcha
GET {{host}}/admin/captcha HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest



### admin login
# @name login
POST {{host}}/admin/login HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest

{
  "username":"admin",
  "password":"123456"
}

@adminToken = {{login.response.body.$.data.token.access_token}}
@refreshToken = {{login.response.body.$.data.token.refresh_token}}

@realToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiMmRjMDRhYmVkYTAwODk0NWFkZGM1ZGViMTNhMDgzNjhlNGQ3NGU5MjAzYjAxYmEyM2Q2NWI3ZTE0MTY3OWVlODVkYzk0MTk1ZWIyMjE1NTIiLCJpYXQiOjE1ODI4NTM3NzEsIm5iZiI6MTU4Mjg1Mzc3MSwiZXhwIjoxNTgyOTQwMTcwLCJzdWIiOiIxIiwic2NvcGVzIjpbIioiXX0.det6DeEY47vmFZsV9j2-ZYbbVU55-__w3V3rFKCupKMMbpcVMzCvndzVdpAcisUQG_JvVspS3Xe-iyKw4NOrVxUdxL5l3XJNpkbFEkb5xIfakUna_fxrY9ofBQzb79SuSJBTDdZUYvIG4_zNckFvMoSDqG6zW4zLbdILOMracVtxK-lL1oJSl0wKOYc-P1jvIrS1A_42dPMAUB6Cxzo99Yi3VI8doUtfmImJa6dJKGuHnVnb_3Ed6YG8xM7U4569xYeia_cq35DaoPfwl_MzztGJQBcvT8fy2iSy76Gz4sD_0nzmRN4pFhZzgybz44wgmIzBSDch1CpMYtONaBr-nM-lGydlbfLNempmbctfJpQ0Gxck9oeA-HvWusPQZ1pRHvdgsvUEG8OAfcu--OSV6j8PbxarMCB-shyAlUqQTPqpk846VS0bbIFnz6AEEU0rr7JdGbTVc__F0Ck9_ALRDPAUyf6tMLLyGnv6iPJD5E38TTFqAiXhMkcJIASgyMck30tWOho6K3C07RTPcjqSiKjos1WG9q67kkvx9DxB4IFMkqSdxtKfCtthsnovMhafhlKNDn3ZXX0zsOpSwfiaUSl2gv5idfqCsYWglK6vhsfObcTgZFnP0VdyNd2e8rIucBWTCjcpa83LYZkf3WbXYOQ8_jAL5XrIKGYIzSeocxU"

### admin info
GET {{host}}/admin/me HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}


### admin logout
POST {{host}}/admin/logout HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### refresh
POST {{host}}/admin/refresh HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest

{
  "refresh_token": "{{refreshToken}}"
}


### oauth token
POST {{host}}/oauth/token HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache

{
  "grant_type":"password",
  "client_id":"2",
  "client_secret":"Ba2swh9tdizTmw4zetCNUi5d734YtNUk9AqGMRJs",
  "scope":"*",    
  "username":"admin",
  "password":"admin",
  "provider":"admins"
}

### token refresh
POST {{host}}/oauth/token HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache

{
  "grant_type":"refresh_token",
  "client_id":"2",
  "client_secret":"En2SBHawG9VrWrUkJqY0FOZHVklvOsazK4DzCSfG",   
  "provider":"admins",
  "refresh_token": "{{refreshToken}}"
}

### permissions list
GET {{host}}/admin/permissions HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### permission
GET {{host}}/admin/permissions/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### update permission
PATCH {{host}}/admin/permissions/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "remark": "test"
}

### create permission
POST {{host}}/admin/permissions HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "name":"test permission3",
  "guard_name":"admin",
  "description":"test",
  "remark":"test",
  "pid":0,
  "type":1
}

### delete permission
DELETE {{host}}/admin/permissions/5 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete permissions
DELETE {{host}}/admin/permissions/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[8,9]
}

### roles list
GET {{host}}/admin/roles HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### role
GET {{host}}/admin/roles/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### create role
POST {{host}}/admin/roles HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "name":"test Role3",
  "guard_name":"admin",
  "description":"test",
  "remark":"test",
  "pid":0,
  "type":1
}

### update role
PATCH {{host}}/admin/roles/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "remark": "test02"
}

### delete role
DELETE {{host}}/admin/roles/5 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete roles
DELETE {{host}}/admin/roles/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[6]
}

### assign permissions to role
POST {{host}}/admin/roles/assign/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[1,2,3]
}

### app notice type
GET {{host}}/admin/admins/field_map HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}


### admins list
GET {{host}}/admin/admins HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "username":"ad",
  "created_at":["2020-01-29T07:50:14.842Z","2020-02-28T07:50:14.842Z"]
}

### admin
GET {{host}}/admin/admins/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### create admin
POST {{host}}/admin/admins HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "username":"test1admin32",
  "password":"123456"
}


### update admin
PATCH {{host}}/admin/admins/12 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "username": "test1admin321"
}

### delete admin
DELETE {{host}}/admin/admins/13 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete admins
DELETE {{host}}/admin/admins/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[5,6]
}

### modify admin password
POST {{host}}/admin/admins/modify/password HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "oldpassword":"123123",
  "password":"1231234",
  "password_confirmation":"1231234"
}

### reset admin password
POST {{host}}/admin/admins/reset/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### assign roles to permission
POST {{host}}/admin/roles/assign/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[1,2,3]
}


### adminlogs list
GET {{host}}/admin/adminlogs HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### adminlog
GET {{host}}/admin/adminlogs/11 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}


### app notice type
GET {{host}}/admin/app_notices/status HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### create app notice
POST {{host}}/admin/app_notices HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "title":"测试通知标题2",
  "content":"测试通知内容",
  "type":1,
  "is_alert":true,
  "access_type":"usr"
}


### app notices list
GET {{host}}/admin/app_notices HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### app notice
GET {{host}}/admin/app_notices/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### update app notice
PATCH {{host}}/admin/app_notices/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "title":"测试通知标题2",
  "content":"测试通知内容222",
  "type":1,
  "is_alert":true,
  "access_type":"usr"
}

### delete app notice
DELETE {{host}}/admin/app_notices/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete app notice
DELETE {{host}}/admin/app_notices/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[1]
}

### article categories list
GET {{host}}/admin/article_categories HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### create article categories
POST {{host}}/admin/article_categories HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "name":"文章类型",
  # "pid":"",
  "is_open":true
}

### update article categories
PATCH {{host}}/admin/article_categories/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "name":"文章类型1",
  # "pid":"",
  "is_open":true
}

### delete article categories
DELETE  {{host}}/admin/article_categories/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete article categories
DELETE  {{host}}/admin/article_categories/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[2]
}





### article list
GET {{host}}/admin/articles HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### article show
GET {{host}}/admin/articles/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### create article
POST {{host}}/admin/articles HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  # "title":"文章类型",
  # "article_category_id":3,
  # "content":"测试内容",
  "status":1,
  "is_recommend":false,
  "is_top":false,
  "weight":20,
  "access_type":"pub"
}

### update article
PATCH {{host}}/admin/articles/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "status":1,
  "is_recommend":true,
  "is_top":false,
  "weight":20,
  "access_type":"pub"
}

### delete article
DELETE {{host}}/admin/articles/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete article
DELETE {{host}}/admin/articles/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[1]
}


### system config list
GET {{host}}/admin/system_configs HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### system config
GET {{host}}/admin/system_configs/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### system config group
GET {{host}}/admin/system_configs/group HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### create system config
POST {{host}}/admin/system_configs HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "flag":"test_flag",
  "title":"标题",
  "config_group":"配置组",
  "value":false,
  "description":"描述",
  "is_open":false
}

### update system config
PATCH {{host}}/admin/system_configs/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "flag":"test_flag",
  "title":"标题2",
  "config_group":"配置组",
  "value":false,
  "description":"描述",
  "is_open":false
}

### delete system config
DELETE {{host}}/admin/system_configs/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete system config
DELETE {{host}}/admin/system_configs/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[1]
}


### status maps list
GET {{host}}/admin/status_maps HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### status map
GET {{host}}/admin/status_maps/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### create status map
POST {{host}}/admin/status_maps HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "table_name":"app_notices",
  "column":"type",
  "status_code":-1,
  "status_description":"所有管理员"
}

### update status map
PATCH {{host}}/admin/status_maps/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "table_name":"app_notices",
  "column":"type",
  "status_code":1,
  "status_description":"所有人1"
}

### delete status map
DELETE  {{host}}/admin/status_maps/1 HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

### batch delete status map
DELETE  {{host}}/admin/status_maps/batch HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer {{adminToken}}

{
  "ids":[1]
}